# Azure DevOps pipeline for PR on Terraform Code

variables:
- group: variable-group

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 5-terratest/vnet

stages:

  # Run Terratest
- stage: Terratest
  jobs:
  - job: terratest
    pool:
      vmImage: ubuntu-20.04
    steps:
    - bash: |
        # Use curl to download the binary
        curl --location --silent --fail --show-error -o terratest_log_parser https://github.com/gruntwork-io/terratest/releases/download/v0.13.13/terratest_log_parser_linux_amd64
        # Make the downloaded binary executable
        chmod +x terratest_log_parser
        # Finally, we place the downloaded binary to a place in the PATH
        sudo mv terratest_log_parser /usr/local/bin
        # Display go version
        go version
        pwd
        ls


